---
# vim: set ft=ansible:
#
# Playbook to verify that hosts under tests are actually Atomic Hosts
#
# Logic borrowed from:
# https://github.com/kubernetes/contrib/blob/master/ansible/roles/common/tasks/main.yml
#
- name: Determine if Atomic Host
  stat:
    path: "/run/ostree-booted"
  register: s
  changed_when: false
  always_run: yes

- name: Init the is_atomic fact
  set_fact:
    is_atomic: false

- name: Set the is_atomic fact
  set_fact:
    is_atomic: true
  when: s.stat.exists

- name: Fail if system is not an Atomic Host
  fail:
    msg: "The system is not an Atomic Host"
  when: not is_atomic

