---
#
#  This role sets up kubernetes apiserver, controller-mgr, and scheduler pods
#
#  - name: pull {{ item }} 
#    command: docker pull registry.access.redhat.com/rhel7/{{ item }}
#    with_items:
#      - kubernetes-apiserver
#      - kubernetes-controller-mgr
#      - kubernetes-scheduler

  - name: pull kubernetes api-server, controller-mgr, scheduler 
    docker:
      image: registry.access.redhat.com/rhel7/{{ item }}
      state: present
    with_items:
      - kubernetes-apiserver
      - kubernetes-controller-mgr
      - kubernetes-scheduler

  - name: make db directory
    file: path=/etc/kubernetes/manifests state=directory mode=0755

  - name: copy apiserver-pod.json, controller-mgr-pod.json, scheduler-pod.json
    copy: 
      src=roles/kubernetes_setup/files/{{ item }}
      dest=/etc/kubernetes/manifests
      owner=root
      group=root
      mode=0644
    with_items:
      - apiserver-pod.json
      - controller-mgr-pod.json
      - scheduler-pod.json

  - name: add kubelet args
    replace:
      dest=/etc/kubernetes/kubelet
      regexp='^KUBELET_ARGS=\"\"'
      replace='KUBELET_ARGS=\"--register-node=true --config=/etc/kubernetes/manifests/\"'

  - name: add kubelet args
    replace:
      dest=/etc/kubernetes/apiserver
      regexp='ServiceAccount,'
      replace=''

  - name: stop docker, etcd, kube-proxy, kubelet
    service: 
      name={{ item }} 
      state=stopped
    with_items:
      - docker
      - etcd
      - kube-proxy
      - kubelet

  - name: start docker, etcd, kube-proxy, kubelet
    service:
      name={{ item }}
      state=started
    with_items:
      - docker
      - etcd
      - kube-proxy
      - kubelet


  - name: enable docker, etcd, kube-proxy, kubelet
    service: 
      name={{ item }}
      enabled=yes
    with_items:
      - docker
      - etcd
      - kube-proxy
      - kubelet

  - name: stop docker, kube-proxy.service, kubelet.service
    service: 
      name={{ item }}
      state=stopped
    with_items:
      - docker
      - kube-proxy.service
      - kubelet.service

  - name: start docker, kube-proxy.service, kubelet.service
    service:
      name={{ item }}
      state=started
    with_items:
      - docker
      - kube-proxy.service
      - kubelet.service

  - name: enable docker, kube-rpoxy.service, kubelet.service
    service: 
      name={{ item }}
      enabled=yes
    with_items:
      - docker
      - kube-proxy.service
      - kubelet.service

  - name: test etcd
    command: curl http://localhost:2379/version
