---
#
# This role creates the docker webserver and database images, then tags and 
# pushes the images to a private registry that is setup in another role.
# 
# Two files containing the are copied to the device under test.  Each Dockerfile
# is modified specifically to pull down its own base OS, mariadb package, and
# apache package.
#    mariadb_cont.tgz
#    web_cont_2.tgz
#

# Need to handle the cases of building the docker containers for each variant

  - name: Fail if ansible_docker0.ipv4.address is not defined
    fail:
      msg: "ansible_docker0.ipv4.address it not defined!"
    when: ansible_docker0.ipv4.address is not defined
    run_once: true

# Red Hat
  - name: copy mariadb_cont.tgz and web_cont_2.tgz 
    copy: 
      src=roles/docker_build_tag_push/files/rhelah/{{ item }} 
      dest=/root
      owner=root
      group=root
      mode=0644
    with_items:
      - mariadb_cont.tgz
      - web_cont_2.tgz
    when: ansible_distribution == "RedHat"

# Fedora 
  - name: copy mariadb_cont.tgz and web_cont_2.tgz
    copy: 
      src=roles/docker_build_tag_push/files/fedora/{{ item }}
      dest=/root
      owner=root
      group=root
      mode=0644
    with_items:
      - mariadb_cont.tgz
      - web_cont_2.tgz
    when: ansible_distribution == "Fedora"

# CentOS
  - name: copy mariadb_cont.tgz and web_cont_2.tgz
    copy: 
      src=roles/docker_build_tag_push/files/centos/{{ item }}
      dest=/root
      owner=root
      group=root
      mode=0644
    with_items:
      - mariadb_cont.tgz
      - web_cont_2.tgz
    when: ansible_distribution == "CentOS"

# Common build, tag, push
  - name: untar db file
    unarchive: 
      src=/root/mariadb_cont.tgz 
      dest=/root/ 
      copy=no

  - name: build db docker image
    command: docker build -t {{ ansible_docker0.ipv4.address}}:5000/dbforweb:latest /root/db

  - name: verify tag
    docker:
      image: '{{ ansible_docker0.ipv4.address }}:5000/dbforweb'
      state: present

  - name: push db to private registry
    command: docker push {{ ansible_docker0.ipv4.address }}:5000/dbforweb:latest

  - name: delete tagged dbforweb image
    command: docker rmi -f {{ ansible_docker0.ipv4.address }}:5000/dbforweb

  - name: download and untar web file
    unarchive: 
      src=/root/web_cont_2.tgz 
      dest=/root/ 
      copy=no

  - name: change IP address in action file before building
    replace: 
      dest=/root/web/action 
      regexp='172.17.42.1' 
      replace={{ ansible_docker0.ipv4.address }}

  - name: build web docker image
    command: docker build -t {{ ansible_docker0.ipv4.address }}:5000/webwithdb:latest /root/web

  - name: verify tag
    docker:
      image: '{{ ansible_docker0.ipv4.address }}:5000/dbforweb'
      state: present

  - name: push web to private registry
    command: docker push {{ ansible_docker0.ipv4.address }}:5000/webwithdb:latest

  - name: delete tagged webwithdb image
    command: docker rmi -f {{ ansible_docker0.ipv4.address }}:5000/webwithdb
