---
# vim: set ft=ansible:
#
# Simple task to verify that the permissions on /tmp are correct.  See
# associated RHBZ 1276775 - https://bugzilla.redhat.com/show_bug.cgi?id=1276775
#
- name: Get info about /tmp
  stat:
    path: /tmp
  register: s

- name: Fail if something on /tmp is fishy
  fail:
    msg: "Permissions or ownership on /tmp is incorrect"
  when: s.stat.mode != "0777" or s.stat.gr_name != "root" or s.stat.pw_name != "root"
