---
# vim: set ft=ansible:
#
# Playbook to collect /etc/machine-id contents and compare
#
- name: Fail if g_host1_name fact are not defined
  fail:
    msg: "The g_host1_name fact is not defined!"
  when: g_host1_name is not defined
  run_once: true

- name: Fail if g_host2_name fact are not defined
  fail:
    msg: "The g_host2_name fact is not defined!"
  when: g_host2_name is not defined
  run_once: true

- name: Fail if g_tmp_dir is not defined
  fail:
    msg: "The g_tmp_dir fact is not defined!"
  when: g_tmp_dir is not defined
  run_once: true

- name: Retrieve contents of /etc/machine-id
  fetch:
    src: /etc/machine-id
    dest: "{{ g_tmp_dir }}/machine-id-{{ inventory_hostname }}"
    flat: yes

- name: Compare machine-id contents for uniqueness
  local_action: command diff "{{ g_tmp_dir }}/machine-id-{{ g_host1_name }}" "{{ g_tmp_dir }}/machine-id-{{ g_host2_name }}"
  register: diff
  run_once: true
  sudo: false
  failed_when: diff.rc != 1
