---
# vim: set ft=ansible:
#
# This role modifies the origin file refspec in order to use
# rpm-ostree upgrade directly
#
# Parameters:
#  refspec (string) - refspec to add to booted origin file
#
- name: Fail if refspec is undefined
  when: ofm_refspec is undefined
  fail:
    msg: "ofm_ refspec is undefined"

- name: Get current booted dir
  command: ostree admin --print-current-dir
  register: current_dir

- name: Replace current refspec
  replace:
    dest: "{{ current_dir.stdout }}.origin"
    regexp: '^(.*refspec=).*$'
    replace: '\1{{ ofm_refspec }}'
