---
# vim: set ft=ansible:
#
# This role will create a new commit on a local repo checkout.
# Assumes the local repo has already been setup.
#
# Parameters:
#   version (string) - version string for commit
#   branch_name (string) - local checkout branch name
#
- name: Fail if version, refspec, or branch_name is undefined
  when: lbc_version is undefined or
        lbc_branch_name is undefined or
        lbc_refspec is undefined
  fail:
    msg: "lbc_version, lbc_refspec, or lbc_branch_name is undefined"

- name: Create a commit with no changes
  command: ostree commit -b {{ lbc_branch_name }} --tree=ref={{ lbc_refspec }} --add-metadata-string version={{ lbc_version }}
